/// One archived report copy — the record of a report command's output being
/// preserved after a run, instead of being silently overwritten by the next
/// one (see docs/RUN_EXPERIENCE_REDESIGN.md §8). Deliberately thin, same
/// spirit as [RunRecord]: enough to show "what was generated, from which
/// run" and to act on (open/download/regenerate), not a full audit trail.
///
/// Has its own [projectId] from day one (unlike [RunRecord], which is
/// missing one — a bug flagged for a later step) since this is new code.
class ReportArchive {
  /// The run this report was generated by — matches the id
  /// [RunProvider.start] returns, not [RunRecord] (which has no id of its
  /// own to join against).
  final String runId;
  final String projectId;
  final String surfaceId;

  /// Display name of the script that produced this report (see
  /// [ScriptEntry.displayName]) — kept as plain text, not a live reference,
  /// since the script itself may be renamed/deleted later.
  final String script;
  final String environment;

  /// `"android"` | `"ios"` | null (web, or platform not applicable).
  final String? platform;

  /// Device UDID the run was bound to, if any.
  final String? device;

  /// The (already `{environment}`/`{udid}`/`{script}`-substituted) report
  /// command text that was actually run — kept so Regenerate can re-run the
  /// exact same command later without re-resolving the pool command.
  final String commandUsed;

  final DateTime generatedAt;

  /// Where the report tool itself wrote its output, inside the project's
  /// own repo — left alone, never modified. May no longer exist by the time
  /// Regenerate is attempted (repo cleaned since).
  final String sourcePath;

  /// Where this app copied [sourcePath]'s contents to, under app-managed
  /// storage — this is what Download/Share/Open actually act on.
  final String archivePath;

  const ReportArchive({
    required this.runId,
    required this.projectId,
    required this.surfaceId,
    required this.script,
    required this.environment,
    this.platform,
    this.device,
    required this.commandUsed,
    required this.generatedAt,
    required this.sourcePath,
    required this.archivePath,
  });

  ReportArchive copyWith({
    DateTime? generatedAt,
    String? archivePath,
  }) =>
      ReportArchive(
        runId: runId,
        projectId: projectId,
        surfaceId: surfaceId,
        script: script,
        environment: environment,
        platform: platform,
        device: device,
        commandUsed: commandUsed,
        generatedAt: generatedAt ?? this.generatedAt,
        sourcePath: sourcePath,
        archivePath: archivePath ?? this.archivePath,
      );

  Map<String, dynamic> toJson() => {
        'runId': runId,
        'projectId': projectId,
        'surfaceId': surfaceId,
        'script': script,
        'environment': environment,
        if (platform != null) 'platform': platform,
        if (device != null) 'device': device,
        'commandUsed': commandUsed,
        'generatedAt': generatedAt.toIso8601String(),
        'sourcePath': sourcePath,
        'archivePath': archivePath,
      };

  /// Never throws — a malformed row is dropped by the caller instead (same
  /// contract as [RunRecord.fromJson]).
  static ReportArchive fromJson(Map<String, dynamic> json) => ReportArchive(
        runId: json['runId'] as String,
        projectId: json['projectId'] as String,
        surfaceId: json['surfaceId'] as String,
        script: json['script'] as String,
        environment: json['environment'] as String,
        platform: json['platform'] as String?,
        device: json['device'] as String?,
        commandUsed: json['commandUsed'] as String,
        generatedAt: DateTime.parse(json['generatedAt'] as String),
        sourcePath: json['sourcePath'] as String,
        archivePath: json['archivePath'] as String,
      );
}
